SET LocalDrive=[TODO DRIVE LETTER]
SET "LocalFolderPath=%LocalDrive%/computerFurnisher"
SET "LocalFolderEntryPointBAT=%LocalFolderPath%/go.bat"
SET "LocalFolderEntryPointPS=%LocalFolderPath%/go.ps1"
SET "LocalFolderDeleteFileFlag=%LocalFolderPath%/delete"
SET "LocalFolderTempSoftware=%LocalFolderPath%/TempSoftware"
SET "LocalFolderExecutables=%LocalFolderPath%/Executables"
SET "LocalFolderScheduledTasks=%LocalFolderPath%/ScheduledTasks"
SET SharedDrive=[TODO SHARED DRIVE I.E z:]
SET SharedDriveLetter=[TODO SHARED DRIVE LETTER WITHOUT COLONI.E z]
SET SharedDriveAddress=[TODO SHAREDDRIVE ADDRESS (i.e. \\contoso\sharedFolder)]
SET DriveRoot=[TODO DRIVE ROOT SAME AS SHAREDDRIVEADDRESS]
SET "SharedFolder=%SharedDrive%\[TODO SUBDIRECTORY TO FOLDER COMPUTER FURNISHER ROOT]"
SET "ComputerFurnisherFolder=%SharedFolder%/[TODO SUB FOLDER CONTAINING SOURCE CODE]"
SET "LogFolder=%SharedFolder%\Logs"
SET "SoftwareFolder=%SharedFolder%\Software"
SET "ScheduledTasksFolder=%SharedFolder%\ScheduledTasks"
SET "ComputerFurnisherScheduledTaskPath=%ScheduledTasksFolder%/Computer-Furnisher/Computer Furnisher Scheduled Task.xml"
SET FileServerName=[TODO FILESERVERNAME FOR CHECKING IF THERE IS A CONNECTION ON FIRST RUN]]
SET StatusFileName=status.xml
SET PrintServer=[NAME OF PrintServer]
SET OfficeKey=[MS OFFICE ACTIVATION KEY]